import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BarraNavegacion from "./componentes/barra";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      style={{background:"black"}}>
        {children}
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        />
        <footer>
          <div style={{width:"60%", marginLeft:"25%", marginTop:"10%"}}>
            <div>
              <img src="redes.png" style={{ width: '189px', height: 'auto' }} />
              <div className="informacionFooter row align-items-start">
                <div className="col">
                  <p>Audio descriptivo</p>
                  <p>Relaciones con inversionistas</p>
                  <p>Avisos legales</p>
                </div>
                <div className="col">
                  <p>Centro de ayuda</p>
                  <p>Empleo</p>
                  <p>Preferencias de cookies</p>
                </div>
                <div className="col">
                  <p>Tarjetas de regalo</p>
                  <p>Términos de uso</p>
                  <p>Información corporativa</p>
                </div>
                <div className="col">
                  <p>Prensa</p>
                  <p>Privacidad</p>
                  <p>Contáctanos</p>
                </div>
              </div>
              <p className="copyright">© 1997-2025 Netflix, Inc.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
